language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - python build.py publish-all

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
